server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:company
    driverClassName: org.h2.Driver
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

isa:
  company:
    url: http://localhost:8081/
    url.delete: /companies/{companyId}
    url.put: /companies/{companyId}
    url.post: /companies

